Traceback (most recent call last):
  File "/build/kitty-git/src/kitty/__main__.py", line 7, in <module>
    main()
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 197, in main
    func(sys.argv[1:])
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 146, in namespaced
    func(args[1:])
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 43, in complete
    os.execvp(kitten_exe(), args)
              ^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/types.py", line 167, in __call__
    self._cached_result = self.__wrapped__()
                          ^^^^^^^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/constants.py", line 84, in kitten_exe
    return os.path.join(os.path.dirname(kitty_exe()), 'kitten')
                                        ^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/types.py", line 167, in __call__
    self._cached_result = self.__wrapped__()
                          ^^^^^^^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/constants.py", line 67, in kitty_exe
    rpath = getattr(sys, 'kitty_run_data').get('bundle_exe_dir')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'sys' has no attribute 'kitty_run_data'
Traceback (most recent call last):
  File "/build/kitty-git/src/kitty/__main__.py", line 7, in <module>
    main()
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 197, in main
    func(sys.argv[1:])
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 146, in namespaced
    func(args[1:])
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 43, in complete
    os.execvp(kitten_exe(), args)
              ^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/types.py", line 167, in __call__
    self._cached_result = self.__wrapped__()
                          ^^^^^^^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/constants.py", line 84, in kitten_exe
    return os.path.join(os.path.dirname(kitty_exe()), 'kitten')
                                        ^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/types.py", line 167, in __call__
    self._cached_result = self.__wrapped__()
                          ^^^^^^^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/constants.py", line 67, in kitty_exe
    rpath = getattr(sys, 'kitty_run_data').get('bundle_exe_dir')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'sys' has no attribute 'kitty_run_data'
Traceback (most recent call last):
  File "/build/kitty-git/src/kitty/__main__.py", line 7, in <module>
    main()
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 197, in main
    func(sys.argv[1:])
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 146, in namespaced
    func(args[1:])
  File "/build/kitty-git/src/kitty/kitty/entry_points.py", line 43, in complete
    os.execvp(kitten_exe(), args)
              ^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/types.py", line 167, in __call__
    self._cached_result = self.__wrapped__()
                          ^^^^^^^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/constants.py", line 84, in kitten_exe
    return os.path.join(os.path.dirname(kitty_exe()), 'kitten')
                                        ^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/types.py", line 167, in __call__
    self._cached_result = self.__wrapped__()
                          ^^^^^^^^^^^^^^^^^^
  File "/build/kitty-git/src/kitty/kitty/constants.py", line 67, in kitty_exe
    rpath = getattr(sys, 'kitty_run_data').get('bundle_exe_dir')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'sys' has no attribute 'kitty_run_data'
